FORMAT: 1A
HOST: http://freeuni-sdp-todo.herokuapp.com/webapi

# air-conditioning-switch

API for retrieving and changing the air conditioner switch status 

## Air conditioning status [/houses/{house_id}/air-conditioning-switch]

+ Parameters
    + house_id (number) - house ID

### Get Air Conditioning Status [GET]

`status` indicates one of the following four conditions: the air conditioning is off `"0"`,
weak stream of cold air `"*"`, strong stream of cold air `"**"`, ventilation without cold air <br>


+ Response 200 (application/json)

        {
            "status" : "0"
        }
    
+ Response 200 (application/json)

        {
            "status" : "*"
        }

+ Response 200 (application/json)

        {
            "status" : "**"
        }

+ Response 200 (application/json)

        {
            "status" : "#"
        }

+ Response 404 (application/json)

### Change Air Conditioning Status [POST]

`set_status` indicates one of the following four conditions: the air conditioning is off `"0"`,
weak stream of cold air `"*"`, strong stream of cold air `"**"`, ventilation without cold air <br>

+ Request (application/json)

        {
            "set_status" : "0"
        }

+ Request (application/json)

        {
            "set_status" : "*"
        }

+ Request (application/json)

        {
            "set_status" : "**"
        }

+ Request (application/json)

        {
            "set_status" : "#"
        }

+ Response 200 (application/json)
+ Response 404 (application/json)